# Generated by Django 5.0.7 on 2024-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_exhibition_end_at_alter_exhibition_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
