# Generated by Django 5.0.7 on 2024-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_exhibition_artworks_alter_exhibition_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='web_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
